<?php

return [
    'permissions' => [
        'dashboard.view',
        'pos.access',
        'pos.checkout',
        'sales.view',
        'sales.pending.settle',
        'sales.correction.manage',
        'reports.view',
        'reports.export',
        'customers.manage',
        'customers.followup.manage',
        'customers.debt.manage',
        'stock-opname.view',
        'stock-opname.manage',
        'stock-transfer.view',
        'stock-transfer.request',
        'stock-transfer.approve',
        'stock-transfer.receive',
        'stock-transfer.export',
        'audit-logs.view',
        'master-data.manage',
        'suppliers.manage',
        'users.manage',
        'permissions.manage',
        'settings.store.manage',
        'settings.notification.manage',
        'approvals.manage',
    ],

    'role_defaults' => [
        'owner' => ['*'],
        'admin' => [
            'dashboard.view',
            'pos.access',
            'pos.checkout',
            'sales.view',
            'sales.pending.settle',
            'sales.correction.manage',
            'reports.view',
            'reports.export',
            'customers.manage',
            'customers.followup.manage',
            'customers.debt.manage',
            'stock-opname.view',
            'stock-opname.manage',
            'stock-transfer.view',
            'stock-transfer.request',
            'stock-transfer.approve',
            'stock-transfer.receive',
            'stock-transfer.export',
            'audit-logs.view',
            'master-data.manage',
            'suppliers.manage',
            'users.manage',
            'permissions.manage',
            'settings.store.manage',
            'settings.notification.manage',
            'approvals.manage',
        ],
        'kasir' => [
            'dashboard.view',
            'pos.access',
            'pos.checkout',
            'sales.view',
            'sales.pending.settle',
        ],
    ],
];
